sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.12.10

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport &&
  sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls
