version: "3"
services:
  app-pgsql:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    expose:
      - "5432"
  app-scala:
    image: pizzaeueu/searchbot
    environment:
      - BOT_TOKEN=PUT_YOUR_BOT_TOKEN_HERE
    command: [
        "sbt",
        "run"
    ]
